version: "3.8"
services:
  web:
    build: .
    depends_on:
      pg-db:
        condition: service_healthy

    restart: on-failure
    environment:
      DB_URL: postgresql://pg-db:5432/code-samurai?user=postgres&password=password
      PORT: 8000
    ports:
      - "8000:8000"
  
  pg-db: 
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: code-samurai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 10