
@url=http://localhost:8000
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IlNZU1RFTV9BRE1JTiIsImlhdCI6MTcxMTQ4NzM0NywiZXhwIjoxNzExNDkwOTQ3fQ.fQhURMaT-mVFcxbiBddzyOFbKTYdrQ1lHCQwzW_zSlY

@refesh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzExNDgyMjU3LCJleHAiOjE3MTIwODcwNTd9.B02DQSYX9KFBklCZXyGb6bcHkcffRkBCdX-YAPkfALE

### health
GET {{url}} HTTP/1.1

### Sign in
POST {{url}}/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "12345678"
}

### Refresh
POST {{url}}/api/auth/refresh-token HTTP/1.1
content-type: application/json

{
  "token": "{{refesh}}"
}


### Sign out
POST {{url}}/api/auth/logout HTTP/1.1
Authorization: {{access}}
content-type: application/json

{
  "token": "{{refesh}}"
}


### test
GET {{url}}/api/users/test HTTP/1.1
Authorization: {{access}}

### profile
GET {{url}}/api/profile HTTP/1.1
Authorization: {{access}}

### add user
POST {{url}}/api/users HTTP/1.1
Authorization : {{access}}
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@xyz.com",
  "password": "12345678",
  "name": "test name"
}

### get all users
GET {{url}}/api/users HTTP/1.1
Authorization: {{access}}

### update role
PUT {{url}}/api/users/5/roles HTTP/1.1
Authorization: {{access}}
Content-Type: application/json

{
  "role_name": "STS_MANAGER"
}

### update user
PUT {{url}}/api/users/5 HTTP/1.1
Authorization: {{access}}
Content-Type: application/json

{
  "username": "test2",
  "email": "test2@xyz.com",
  "name": "test2 name",
  "active": true,
  "banned": false
}