
@url=http://localhost:8000
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6WyJTWVNURU1fQURNSU4iXSwiaWF0IjoxNzExNDQ4OTM4LCJleHAiOjE3MTE0NTI1Mzh9.kV9X4BbUSkHjM_V-n0KbVFLiRA_0UtK9DDlXeMeVk8c

### health
GET {{url}} HTTP/1.1

### Sign in
POST {{url}}/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "12345678"
}

### test
GET {{url}}/api/users/test HTTP/1.1
Authorization: Bearer {{access}}
