
@url=http://localhost:8000
@access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6WyJTWVNURU1fQURNSU4iXSwiaWF0IjoxNzExNDUwMTE0LCJleHAiOjE3MTE0NTM3MTR9.uPRx7d5kGLgq6GFxjeOrVzJsdku6OR3smaUMq9AcsMc

### health
GET {{url}} HTTP/1.1

### Sign in
POST {{url}}/api/auth/login HTTP/1.1
content-type: application/json

{
  "username": "unassigned",
  "password": "12345678"
}

### test
GET {{url}}/api/users/test HTTP/1.1
Authorization: {{access}}

### profile
GET {{url}}/api/profile HTTP/1.1
Authorization: {{access}}